### ISSUE TITLE
hash操作无法正常显示value

### ISSUE THREAD

**Issue by hiABandon** [huifer/view-redis#1]
- 点击查看某个hash
![图片](https://user-images.githubusercontent.com/36032188/96445366-5e0d3f00-1242-11eb-9d69-c327160bfc0b.png)
- redis中，该键确实有值
![图片](https://user-images.githubusercontent.com/36032188/96445624-c9efa780-1242-11eb-954d-7c74c435cf12.png)

**Comment by huifer** [comment]
Thank you for your questions, which will be revised later. It will be changed to servlet post for parameter passing
